### ISSUE TITLE
Plugin crash when large number of changes are performed in a short time

### ISSUE THREAD

**Issue by drockcode** [vinsworldcom/nppLocationNavigate#2]
The plugin will crash anytime a large number of changes are performed on a file in a short amount of time:
•If you perform a Find / Replace with a large number of replacements in a single file.
•You can also crash the plugin by doing a large column mode selection (e.g. over 5000 lines), and typing in several letters.

Adding std::mutex locks and unlocks around all accesses to ActionDataList appears to resolve the issue. I have created a pull request with my suggested code changes: [Pull Request](https://github.com/vinsworldcom/nppLocationNavigate/pull/1)

**Comment by vinsworldcom** [comment]
Tried patch, still crashes for me.  Can't get 64-bit to compile either.  Abandoning work on this module.
