### ISSUE TITLE
plugin crash fixs

### ISSUE THREAD

**Issue by ewuc** [vinsworldcom/nppLocationNavigate#3]
I have found how to fix certain crash from
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/240#issuecomment-361846617

There is another crash when closing notepad++, not sure if above solution will fix this as well.

**Comment by vinsworldcom** [comment]
Already tried that.  My comments are there.  Didn't work.  This effort is no longer supported in favor of [ChagnedLines](https://github.com/vinsworldcom/nppChangedLines).
